# Generated by Django 3.0.8 on 2020-07-31 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_name'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('school', models.CharField(choices=[('umich', 'University of Michigan Ann Arbor')], default='umich', max_length=100)),
                ('name', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
