# Generated by Django 3.0.8 on 2020-07-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_tutorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='school',
            field=models.CharField(max_length=100),
        ),
    ]
