# Generated by Django 3.0.8 on 2020-07-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200731_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='subjects',
            field=models.TextField(default='none', max_length=400, verbose_name='subjects'),
        ),
    ]
