# Generated by Django 3.0.8 on 2020-08-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_tutorprofile_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='clients',
            field=models.CharField(default='none', max_length=50, verbose_name='clients'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='major',
            field=models.CharField(default='none', max_length=50, verbose_name='major'),
        ),
    ]
