# Generated by Django 3.0.8 on 2020-08-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20200801_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='accommodations',
            field=models.IntegerField(default=0, verbose_name='accommodations'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='clients',
            field=models.IntegerField(default=0, verbose_name='clients'),
        ),
    ]
