# Generated by Django 3.0.8 on 2020-07-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='type',
            field=models.CharField(default='none', max_length=50, verbose_name='type'),
        ),
    ]
